<?$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/1jquery.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/html5shiv.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/jquery-ui.min.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/jquery.easing.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/jquery.hoverup.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/jquery.metadata.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/jquery.stellar.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/respond.min.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/01_jquery/wp.app.js", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/01_main/02 bootstrap/bootstrap.min.css", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/01_main/02 bootstrap/bootstrap.min.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/bootstrap-mobile-menu/wp.app.js", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/02_assets/fancybox/jquery.fancybox.css", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/fancybox/jquery.fancybox.pack.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/hover-dropdown/bootstrap-hover-dropdown.min.js", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/02_assets/layerslider/css/layerslider.css", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/layerslider/js/greensock.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/layerslider/js/layerslider.kreaturamedia.jquery.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/layerslider/js/layerslider.transitions.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/milestone-counter/jquery.countTo.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/mixitup/jquery.mixitup.init.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/mixitup/jquery.mixitup.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/page-scroller/jquery.ui.totop.min.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/responsive-mobile-nav/js/jquery.dlmenu.autofill.js", true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/responsive-mobile-nav/js/jquery.dlmenu.js", true);
$APPLICATION->AddHeadString('<!--[if lt IE 9]><link href="/bitrix/templates/simai.school/framework/include/02_assets/sky-forms/sky-forms-ie8.css"<![endif]-->', true);
$APPLICATION->AddHeadScript("/bitrix/templates/simai.school/framework/include/02_assets/waypoints/waypoints.min.js", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/03_icons/font-awesome/css/font-awesome.min.css", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/04_template/bg.css", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/04_template/boomerang.css", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/04_template/helpers.css", true);
$APPLICATION->SetAdditionalCss("/bitrix/templates/simai.school/framework/include/04_template/visual.css", true);
?>